Repository GQCG/GQCP, pull requests merged in 2020-03, with the labels that each got.

#551 DOCI bindings
  gqcpy/gqcpy.cpp
  gqcpy/src/ONVBasis/CMakeLists.txt
  gqcpy/src/ONVBasis/SeniorityZeroONVBasis.cpp
  gqcpy/src/QCMethod/CI/CIEnvironment.cpp
Labels: python bindings

#557 Update DOCINewtonOrbitalOptimizer
  gqcp/include/ONVBasis/SeniorityZeroONVBasis.hpp
  gqcp/include/QCMethod/CI/CMakeLists.txt
  gqcp/include/QCMethod/CI/DOCINewtonOrbitalOptimizer.hpp
  gqcp/include/QCModel/CI/LinearExpansion.hpp
  gqcp/src/QCMethod/CI/CMakeLists.txt
  gqcp/src/QCMethod/CI/DOCINewtonOrbitalOptimizer.cpp
  gqcp/tests/QCMethod/CI/CMakeLists.txt
  gqcp/tests/QCMethod/CI/DOCINewtonOrbitalOptimizer_test.cpp
  gqcpy/gqcpy.cpp
  gqcpy/src/QCMethod/CI/CMakeLists.txt
  gqcpy/src/QCMethod/CI/DOCINewtonOrbitalOptimizer.cpp
  gqcpy/src/QCMethod/CI/DOCINewtonOrbitalOptimizer_factory.cpp
Labels: maintenance, python bindings

#561 USQOneElectronOperator
  gqcp/include/Operator/SecondQuantized/CMakeLists.txt
  gqcp/include/Operator/SecondQuantized/USQOneElectronOperator.hpp
  gqcp/tests/Operator/SecondQuantized/CMakeLists.txt
  gqcp/tests/Operator/SecondQuantized/SQOneElectronOperator_test.cpp
  gqcp/tests/Operator/SecondQuantized/USQOneElectronOperator_test.cpp
Labels: feature
