Repository GQCG/GQCP, pull requests merged in 2020-08, with the labels that each got.

#603 Bugfix: Travis Python support (closes #602)
  .travis.yml
Labels: Python, bug, devops

#615 Rename workflows
  .github/workflows/conda.yml
  .github/workflows/gqcp.yml
Labels: devops, refactor

#625 hotfix/deploy_website
  .github/workflows/docusaurus.yml
Labels: devops, website

#631 Maintenance
  gqcp/benchmarks/QCMethod/DOCI/doci_case.cpp
  gqcp/include/Basis/CMakeLists.txt
  gqcp/include/Basis/SpinResolvedTransformationMatrix.hpp
  gqcp/include/Basis/SpinorBasis/GSpinorBasis.hpp
  gqcp/include/Basis/SpinorBasis/USpinorBasis.hpp
  gqcp/include/Basis/TransformationMatrix.hpp
  gqcp/include/Mathematical/Representation/QCMatrix.hpp
  gqcp/include/Mathematical/Representation/QCRankFourTensor.hpp
  gqcp/include/ONVBasis/SpinResolvedONV.hpp
  gqcp/include/Operator/SecondQuantized/SQHamiltonian.hpp
  gqcp/include/Operator/SecondQuantized/SQOneElectronOperator.hpp
  gqcp/include/Operator/SecondQuantized/SQTwoElectronOperator.hpp
  gqcp/include/Operator/SecondQuantized/USQHamiltonian.hpp
  gqcp/include/Operator/SecondQuantized/USQOneElectronOperator.hpp
  gqcp/include/Operator/SecondQuantized/USQTwoElectronOperator.hpp
  gqcp/include/Processing/DensityMatrices/SpinResolvedOneDM.hpp
  gqcp/include/Processing/DensityMatrices/SpinResolvedTwoDM.hpp
  gqcp/include/Processing/DensityMatrices/TwoDM.hpp
  gqcp/include/Processing/Properties/expectation_values.hpp
  gqcp/include/QCMethod/Geminals/AP1roG.hpp
  gqcp/include/QCMethod/Geminals/PSEnvironment.hpp
  gqcp/include/QCMethod/Geminals/vAP1roG.hpp
  gqcp/include/QCModel/CI/LinearExpansion.hpp
  gqcp/include/QCModel/HF/RHF.hpp
  gqcp/include/QCModel/HF/UHF.hpp
  gqcp/include/gqcp.hpp
  gqcp/src/ONVBasis/BaseFrozenCoreONVBasis.cpp
  gqcp/src/ONVBasis/SeniorityZeroONVBasis.cpp
  gqcp/src/ONVBasis/SpinResolvedONV.cpp
  gqcp/src/ONVBasis/SpinResolvedONVBasis.cpp
  gqcp/src/ONVBasis/SpinResolvedSelectedONVBasis.cpp
  gqcp/src/ONVBasis/SpinUnresolvedONVBasis.cpp
  gqcp/src/Processing/Properties/RHFElectricalResponseSolver.cpp
  gqcp/src/QCMethod/CI/HamiltonianBuilder/DOCI.cpp
  gqcp/src/QCMethod/CI/HamiltonianBuilder/FCI.cpp
  gqcp/src/QCMethod/CI/HamiltonianBuilder/SelectedCI.cpp
  gqcp/src/QCMethod/OrbitalOptimization/JacobiOrbitalOptimizer.cpp
  gqcp/src/QCMethod/OrbitalOptimization/Localization/ERNewtonLocalizer.cpp
  gqcp/src/QCMethod/OrbitalOptimization/QCMethodNewtonOrbitalOptimizer.cpp
  gqcp/src/QCModel/Geminals/AP1roG.cpp
  gqcp/src/QCModel/Geminals/AP1roGGeminalCoefficients.cpp
  gqcp/src/QCModel/Geminals/vAP1roG.cpp
  gqcp/tests/Basis/SpinorBasis/USpinorBasis_test.cpp
  gqcp/tests/ONVBasis/SpinResolvedONV_test.cpp
  gqcp/tests/ONVBasis/SpinResolvedSelectedONVBasis_test.cpp
  gqcp/tests/ONVBasis/SpinUnresolvedONV_test.cpp
  gqcp/tests/Operator/SecondQuantized/SQOneElectronOperator_test.cpp
  gqcp/tests/Operator/SecondQuantized/SQTwoElectronOperator_test.cpp
  gqcp/tests/Operator/SecondQuantized/USQOneElectronOperator_test.cpp
  gqcp/tests/Operator/SecondQuantized/USQTwoElectronOperator_test.cpp
  gqcp/tests/Processing/DensityMatrices/CIDMCalculators/GeneralDMCalculator_test.cpp
  gqcp/tests/Processing/Properties/expectation_values_test.cpp
  gqcp/tests/QCMethod/Applications/AtomicDecompositionParameters_test.cpp
  gqcp/tests/QCMethod/Applications/constrained_RHF_test.cpp
  gqcp/tests/QCMethod/CI/DOCI_test.cpp
  gqcp/tests/QCMethod/Geminals/AP1roGJacobiOrbitalOptimizer_test.cpp
  gqcp/tests/QCMethod/HF/RHF/RHFSCFEnvironment_test.cpp
  gqcpy/src/Basis/SpinorBasis/USpinorBasis_bindings.cpp
  gqcpy/src/ONVBasis/SpinResolvedONV_bindings.cpp
Labels: C++, refactor

#619 Improve documentation
  site/docs/developer_documentation/getting_started.md
  site/docs/developer_documentation/introduction.md
Labels: documentation, website

#642 Feature/docker
  .devcontainer/devcontainer.json
  .github/workflows/docker-gqcp-dev.yml
  Dockerfile
  docker-compose.yml
  gqcp/tests/Basis/Integrals/IntegralCalculator_test.cpp
  site/docs/developer_documentation/getting_started.md
Labels: feature

#647 Enable MacOS Conda package build (closes #597).
  .github/workflows/conda.yml
Labels: feature
