Repository GQCG/GQCP, pull requests merged in 2020-12, with the labels that each got.

#832 Fix CI/CD website.
  .github/workflows/website.yml
  site/docs/api.md
Labels: bug

#831 Implement try-out button (closes #813, #815, #816)
  .devcontainer/devcontainer.json
  .github/workflows/ci-cd-conda.yml
  .github/workflows/docker-gqcp-deploy.yml
  README.md
  conda/build.sh
  conda/conda_build_config.yaml
  conda/meta.yaml
  docker/Dockerfile
  environment.yml
  gqcpy/examples/README.md
  gqcpy/examples/try_it_out.ipynb
  media/examples.png
Labels: devops

#828 Additional bindings regarding Transformations.
  gqcpy/include/interfaces.hpp
  gqcpy/src/Basis/Transformations/UTransformation_bindings.cpp
  gqcpy/src/DensityMatrix/SpinResolved1DM_bindings.cpp
Labels: Python, feature

#839 Implement complex GHF bindings.
  gqcp/include/Basis/SpinorBasis/SimpleSpinorBasis.hpp
  gqcp/include/Operator/SecondQuantized/SQHamiltonian.hpp
  gqcp/include/QCMethod/HF/GHF/GHF.hpp
  gqcp/include/QCMethod/HF/GHF/GHFDensityMatrixCalculation.hpp
  gqcp/include/QCMethod/HF/GHF/GHFElectronicEnergyCalculation.hpp
  gqcp/include/QCMethod/HF/GHF/GHFFockMatrixCalculation.hpp
  gqcp/include/QCMethod/HF/GHF/GHFSCFEnvironment.hpp
  gqcp/include/QCMethod/QCStructure.hpp
  gqcp/include/QCModel/HF/GHF.hpp
  gqcpy/examples/HF Stability.ipynb
  gqcpy/gqcpy.cpp
  gqcpy/src/Basis/SpinorBasis/GSpinorBasis_bindings.cpp
  gqcpy/src/Basis/Transformations/GTransformation_bindings.cpp
  gqcpy/src/Mathematical/Algorithm/IterativeAlgorithm_bindings.cpp
  gqcpy/src/Operator/SecondQuantized/SQHamiltonian_bindings.cpp
  gqcpy/src/QCMethod/HF/GHF/GHFSCFEnvironment_bindings.cpp
  gqcpy/src/QCMethod/HF/GHF/GHFSCFSolver_bindings.cpp
  gqcpy/src/QCMethod/HF/GHF/GHF_bindings.cpp
  gqcpy/src/QCMethod/QCStructure_bindings.cpp
Labels: C++, Python

#858 Add extra test for Dyson amplitudes
  gqcp/include/Processing/Properties/DysonOrbital.hpp
  gqcp/tests/Processing/Properties/DysonOrbital_test.cpp
Labels: C++, testing

#861 Community improvements
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/maintenance-request.md
  .github/ISSUE_TEMPLATE/question.md
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation
