Repository GQCG/GQCP, pull requests merged in 2020-11, with the labels that each got.

#764 PR: Change class to struct for traits.
  gqcp/include/Basis/SpinorBasis/GSpinorBasis.hpp
  gqcp/include/Basis/SpinorBasis/RSpinOrbitalBasis.hpp
  gqcp/include/DensityMatrix/G1DM.hpp
  gqcp/include/DensityMatrix/G2DM.hpp
  gqcp/include/DensityMatrix/Orbital1DM.hpp
  gqcp/include/DensityMatrix/SpinDensity1DM.hpp
  gqcp/include/DensityMatrix/SpinResolved1DMComponent.hpp
  gqcp/include/DensityMatrix/SpinResolved2DMComponent.hpp
  gqcp/include/Operator/SecondQuantized/EvaluatableScalarRSQOneElectronOperator.hpp
  gqcp/include/Operator/SecondQuantized/SQOperatorStorageBase.hpp
Labels: C++, refactor

#767 Make areEqualEigenvectors part of VectorX.
  gqcp/include/Mathematical/Representation/Matrix.hpp
  gqcp/include/QCModel/CI/LinearExpansion.hpp
  gqcp/include/Utilities/CMakeLists.txt
  gqcp/include/Utilities/linalg.hpp
  gqcp/include/gqcp.hpp
  gqcp/src/Mathematical/Optimization/Eigenproblem/Eigenpair.cpp
  gqcp/src/Utilities/CMakeLists.txt
  gqcp/src/Utilities/linalg.cpp
  gqcp/tests/Basis/Integrals/Interfaces/LibintInterfacer_test.cpp
  gqcp/tests/Mathematical/Optimization/Eigenproblem/EigenproblemSolver_test.cpp
  gqcp/tests/Mathematical/Representation/Matrix_test.cpp
  gqcp/tests/Operator/SecondQuantized/SQHamiltonian_test.cpp
  gqcp/tests/Operator/SecondQuantized/SimpleSQTwoElectronOperator_test.cpp
  gqcp/tests/Operator/SecondQuantized/USQTwoElectronOperator_test.cpp
  gqcp/tests/QCMethod/HF/GHF/QCMethod_GHF_test.cpp
  gqcp/tests/QCMethod/HF/RHF/QCMethod_RHF_test.cpp
  gqcp/tests/QCMethod/HF/UHF/QCMethod_UHF_test.cpp
  gqcp/tests/Utilities/CMakeLists.txt
  gqcp/tests/Utilities/linalg_test.cpp
Labels: C++, refactor

#804 Bugfix: refactor to new GA api (closes #800).
  .devcontainer/devcontainer.json
  .github/workflows/build-and-test.yml
  .github/workflows/conda-build.yml
  .github/workflows/conda-deploy.yml
  .github/workflows/docker-gqcp-build.yml
  .github/workflows/docker-gqcp-deploy.yml
  .github/workflows/docker-gqcp-dev.yml
  Dockerfile
  Dockerfile-dev
  environment.yml
  gqcp/include/QCModel/HF/StabilityMatrices/CMakeLists.txt
  gqcp/include/gqcp.hpp
Labels: devops

#797 Dyson orbitals implementation.
  gqcp/include/Processing/Properties/CMakeLists.txt
  gqcp/include/Processing/Properties/DysonOrbital.hpp
  gqcp/include/Processing/Properties/properties.hpp
  gqcp/include/gqcp.hpp
  gqcp/src/Processing/Properties/properties.cpp
  gqcp/tests/Processing/Properties/CMakeLists.txt
  gqcp/tests/Processing/Properties/DysonOrbital_test.cpp
  gqcp/tests/Processing/Properties/properties_test.cpp
  gqcpy/gqcpy.cpp
  gqcpy/src/Processing/Properties/CMakeLists.txt
  gqcpy/src/Processing/Properties/DysonOrbital_bindings.cpp
Labels: C++, feature
